package promptfilter

import "regexp"

const (
	lateralMovementTechniqueEN = `(?:lateral\s+movement|pass[-\s]?the[-\s]?(?:hash|ticket)|psexec|wmi(?:\s+|-)?exec)`
	lateralMovementTargetEN    = `(?:domain\s+controller|domain|(?:target|victim|other|remote|compromised)\s+(?:hosts?|servers?|systems?|machines?|endpoints?))`
	lateralMovementHarmEN      = `(?:(?:compromise|take\s+over)\s+(?:the\s+)?` + lateralMovementTargetEN + `|pivot(?:\s+(?:into|to|across|through))\s+(?:the\s+)?(?:internal\s+network|` + lateralMovementTargetEN + `)|execute\s+commands?\s+on\s+(?:the\s+)?` + lateralMovementTargetEN + `|without\s+(?:permission|authorization)|pass[-\s]?the[-\s]?(?:hash|ticket))`
	lateralMovementTechniqueZH = `(?:横向移动|横向渗透|哈希传递|票据传递|psexec|wmiexec)`
	lateralMovementTargetZH    = `(?:域控|域|(?:内网|域内)?(?:目标|其他|受害|远程|失陷|受控)(?:主机|服务器|系统|设备|终端))`
	lateralMovementHarmZH      = `(?:(?:接管|拿下)` + lateralMovementTargetZH + `|(?:在|对)(?:未授权|未经许可)(?:的)?(?:目标|其他|受害|远程)?(?:主机|服务器|系统|设备|终端)(?:上)?执行命令|未经(?:授权|许可)[^。！？；\n]{0,16}执行命令|哈希传递|票据传递)`

	operationalLateralMovementRequestPattern = `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)\b(?:execute|perform|conduct|launch|use)\b[^.!?;:\n]{0,56}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,64}\b` + lateralMovementHarmEN + `\b|\b(?:how\s+to|show\s+me\s+how\s+to)\b[^.!?;:\n]{0,56}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,64}\b` + lateralMovementHarmEN + `\b|\b(?:use|abuse|replay)\b[^.!?;:\n]{0,64}\b(?:stolen\s+(?:domain\s+)?(?:credentials?|hash(?:es)?|tickets?))\b[^.!?;:\n]{0,64}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,64}\b` + lateralMovementHarmEN + `\b|(?:^|[。！？；：\n]|请|请你|帮我|给我|我要|需要你)(?:直接|立即|马上)?(?:执行|实施|发起|使用|利用)[^。！？；\n]{0,40}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,56}` + lateralMovementHarmZH + `|(?:如何|怎么)[^。！？；\n]{0,40}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,56}` + lateralMovementHarmZH + `|(?:使用|利用|复用|重放)[^。！？；\n]{0,32}(?:已?窃取的?(?:域)?凭据|域凭据|密码哈希|票据)[^。！？；\n]{0,48}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,48}` + lateralMovementHarmZH
	operationalLateralMovementCommandPattern = `(?i)\b(?:give|provide|write|generate)\b[^.!?;:\n]{0,48}(?:(?:commands?|steps?|script|payload)[^.!?;:\n]{0,40}\b` + lateralMovementTechniqueEN + `\b|\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,40}(?:commands?|steps?|script|payload))[^.!?;:\n]{0,64}\b` + lateralMovementHarmEN + `\b|\b(?:give|provide|write|generate)\b[^.!?;:\n]{0,48}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,48}\b` + lateralMovementHarmEN + `\b[^.!?;:\n]{0,40}\b(?:commands?|steps?|script|payload)\b|(?:^|[。！？；：\n]|请|请你|帮我|给我|我要|需要你)(?:直接|立即|马上)?(?:给出|提供|编写|生成)[^。！？；\n]{0,48}(?:(?:命令|脚本|载荷|步骤|教程)[^。！？；\n]{0,40}` + lateralMovementTechniqueZH + `|` + lateralMovementTechniqueZH + `[^。！？；\n]{0,40}(?:命令|脚本|载荷|步骤|教程))[^。！？；\n]{0,48}` + lateralMovementHarmZH + `|(?:^|[。！？；：\n]|请|请你|帮我|给我|我要|需要你)(?:直接|立即|马上)?(?:给出|提供|编写|生成)[^。！？；\n]{0,48}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,48}` + lateralMovementHarmZH + `[^。！？；\n]{0,40}(?:命令|脚本|载荷|步骤|教程)`
	operationalLateralMovementControlPattern = `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)\b(?:execute|perform|conduct|launch|use)\b[^.!?;:\n]{0,56}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,64}\bcontrol\s+(?:the\s+)?` + lateralMovementTargetEN + `(?:\s*(?:$|[.!?;:])|\s+(?:and|then|to)\s+(?:execute|run|deploy|compromise|take\s+over)\b|\s+(?:commands?|steps?|script|payload)\b)|(?:^|[。！？；：\n]|请|请你|帮我|给我|我要|需要你)(?:直接|立即|马上)?(?:执行|实施|发起|使用|利用)[^。！？；\n]{0,40}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,56}控制` + lateralMovementTargetZH + `(?:\s*(?:$|[。！？；：])|(?:并|然后|以便)(?:执行命令|接管|拿下)|的(?:命令|脚本|载荷|步骤|教程))` + `|\b(?:give|provide|write|generate)\b[^.!?;:\n]{0,64}\b` + lateralMovementTechniqueEN + `\b[^.!?;:\n]{0,56}\bcontrol\s+(?:the\s+)?` + lateralMovementTargetEN + `(?:\s*(?:$|[.!?;:])|\s+(?:commands?|steps?|script|payload)\b)|(?:^|[。！？；：\n]|请|请你|帮我|给我|我要|需要你)(?:直接|立即|马上)?(?:给出|提供|编写|生成)[^。！？；\n]{0,64}` + lateralMovementTechniqueZH + `[^。！？；\n]{0,56}控制` + lateralMovementTargetZH + `(?:\s*(?:$|[。！？；：])|的(?:命令|脚本|载荷|步骤|教程))`

	// Minor-safety enforcement intentionally uses grammatical intent instead of
	// proximity between generic software words such as "create" and "children".
	// This keeps child tasks, child processes, React children, minor versions,
	// education, and safety-classifier text out of the terminal rule while still
	// blocking explicit grooming, sexual exploitation, and illegal material.
	minorTargetEN                = `(?:minors?|children|child|schoolchildren|kids?|preteens?|teens?|teenagers?|adolescents?|youths?|toddlers?|infants?|underage(?:\s+(?:people|persons?|users?|girls?|boys?|students?|kids?|teens?))?|(?:[0-9]|1[0-7])\s*[- ]?\s*year\s*[- ]?\s*olds?)`
	minorUnambiguousHarmActionEN = `(?:sexualize|sexually\s+(?:exploit|abuse|assault)|molest)`
	minorAmbiguousHarmActionEN   = `(?:exploit|abuse)`
	minorAmbiguousHarmSuffixEN   = `(?:\s*(?:$|[.!?,;:])|\s+(?:repeatedly|deliberately|sexually|physically|financially)\b|\s+for\s+(?:forced\s+labor|labor|profit|money|commercial\s+gain|sexual\s+(?:purposes?|content)|trafficking)\b)`
	minorDirectHarmTargetEN      = `(?:\s+(?:an?|the|young|vulnerable|specific|targeted|real|actual)){0,3}\s+\b` + minorTargetEN + `\b`
	minorGroomingNoiseEN         = `(?:\s+(?:tasks?|components?|nodes?|items?|records?|examples?|samples?)){0,2}`
	minorGroomingMethodEN        = `(?:\s+(?:(?:through|via|using|over)\s+(?:(?:private|direct|online|encrypted|social[-\s]?media)\s+){0,2}(?:messages?|dms?|chats?|conversations?|social\s+media|messaging\s+apps?)|online|while\s+(?:hiding|concealing)\s+(?:the\s+)?(?:intent|purpose)|for\s+sexual\s+(?:purposes?|content)))`
	minorDirectGroomingRequestEN = `\bgroom\b` + minorDirectHarmTargetEN + minorGroomingNoiseEN + minorGroomingMethodEN
	minorGroomingHowToRequestEN  = `\b(?:how\s+to|show\s+(?:me|us)\s+how\s+to|tell\s+(?:me|us)\s+how\s+to|explain\s+how\s+to)\s+groom\b` + minorDirectHarmTargetEN
	minorDirectHarmRequestEN     = `\b` + minorUnambiguousHarmActionEN + `\b` + minorDirectHarmTargetEN + `|\b` + minorAmbiguousHarmActionEN + `\b` + minorDirectHarmTargetEN + minorAmbiguousHarmSuffixEN + `|` + minorDirectGroomingRequestEN + `|` + minorGroomingHowToRequestEN
	minorIllegalMaterialEN       = `(?:csam|child\s+sexual\s+abuse\s+material|child\s+porn(?:ography)?|child\s+pornographic\s+(?:content|material|images?|videos?))`
	minorMaterialObjectEN        = `(?:\s+(?:me|us))?(?:\s+(?:an?|the|some|new|actual|real|explicit|illegal|this|that)){0,4}\s+` + minorIllegalMaterialEN + `(?:\s+(?:content|material|images?|videos?|files?))?`
	minorMaterialRequestEN       = `\b(?:create|generate|produce|make|provide|give|share|distribute|publish|upload|sell|trade|send|forward|relay|reproduce|replicate|download|obtain|request|receive|fetch|find|acquire|locate|source|procure)\b` + minorMaterialObjectEN
	minorMaterialGerundActionEN  = `(?:creating|generating|producing|making|providing|giving|sharing|distributing|publishing|uploading|selling|trading|sending|forwarding|relaying|reproducing|replicating|downloading|obtaining|requesting|receiving|fetching|finding|acquiring|locating|sourcing|procuring)`
	minorRequestedGerundEN       = `(?:\bhelp\s+(?:me|us)(?:\s+with)?\s+|\bassist\s+(?:me|us)\s+in\s+|\b(?:can|could|would)\s+you\s+(?:please\s+)?help\s+(?:me|us)(?:\s+with)?\s+|\b(?:please|kindly)\s+)` + minorMaterialGerundActionEN + `\b` + minorMaterialObjectEN
	minorPassiveMaterialEN       = `\b(?:i|we)\s+(?:need|want|would\s+like)\b(?:\s+(?:some|the|new|actual|real|explicit|illegal)){0,3}\s+` + minorIllegalMaterialEN + `(?:\s+(?:content|material|images?|videos?|files?))?\s+(?:created|generated|produced|provided|shared|sent|uploaded|downloaded|obtained)\b`
	minorCausativeMaterialEN     = `\b(?:please\s+|kindly\s+)?(?:have|get)\b(?:\s+(?:some|the|new|actual|real|explicit|illegal)){0,3}\s+` + minorIllegalMaterialEN + `(?:\s+(?:content|material|images?|videos?|files?))?\s+(?:created|generated|produced|provided|shared|sent|uploaded|downloaded|obtained)(?:\s+for\s+(?:me|us))?\b`
	minorProgressiveCueEN        = `\b(?:start|begin|continue|keep|resume)\s+`
	minorProgressiveHarmEN       = minorProgressiveCueEN + `(?:grooming\b` + minorDirectHarmTargetEN + minorGroomingNoiseEN + minorGroomingMethodEN + `|(?:sexualizing|sexually\s+(?:exploiting|abusing|assaulting)|molesting)\b` + minorDirectHarmTargetEN + `|(?:exploiting|abusing)\b` + minorDirectHarmTargetEN + minorAmbiguousHarmSuffixEN + `|` + minorMaterialGerundActionEN + `\b` + minorMaterialObjectEN + `)`
	minorMediaModifiersEN        = `(?:\s+(?:an?|the|some|new|actual|real|realistic|photorealistic|ai[-\s]?generated|high[-\s]?resolution)){0,5}`
	minorSexualMediaAdjectiveEN  = `(?:sexual|sexually\s+explicit|explicit|nude|pornographic|abusive)`
	minorSexualMediaObjectEN     = minorMediaModifiersEN + `(?:\s+` + minorSexualMediaAdjectiveEN + `){1,3}\s+(?:images?|photos?|videos?|content|material)\s+(?:of|involving|featuring|depicting)\s+(?:an?\s+|the\s+)?` + minorTargetEN
	minorTargetSideMediaObjectEN = minorMediaModifiersEN + `\s+(?:images?|photos?|videos?|content|material)\s+of\s+(?:an?\s+|the\s+)?(?:nude|sexualized|sexually\s+exploited|pornographic)\s+` + minorTargetEN
	minorSexualMediaRequestEN    = `\b(?:create|generate|produce|make|share|distribute|publish|upload)\b(?:` + minorSexualMediaObjectEN + `|` + minorTargetSideMediaObjectEN + `)\b`
	minorSexualizingContentEN    = `\b(?:create|generate|produce|make|write)\b` + minorMediaModifiersEN + `\s+(?:images?|videos?|content|material|messages?)\s+(?:that|which|designed\s+to|intended\s+to)\s+(?:sexualizes?|sexually\s+exploits?|grooms?)\s+(?:an?\s+|the\s+)?` + minorTargetEN + `\b`
	minorGroomingArtifactEN      = `(?:grooming|enticement)\s+(?:messages?|scripts?|playbooks?|campaigns?|strateg(?:y|ies)|dms?|conversation\s+starters?)`
	minorGroomingArtifactRequest = `\b(?:create|generate|write|draft|provide|give)\b(?:\s+(?:me|us))?(?:\s+(?:an?|the|some|new|targeted|private)){0,4}\s+` + minorGroomingArtifactEN + `\s+(?:targeting|for|to)\s+(?:an?\s+|the\s+)?` + minorTargetEN + `\b|\b(?:create|generate|write|draft|provide|give)\b(?:\s+(?:me|us))?(?:\s+(?:an?|the|some|new|targeted|private)){0,4}\s+(?:messages?|scripts?|dms?|conversation\s+starters?|instructions?|steps?|plans?|strateg(?:y|ies)|playbooks?|campaigns?)\s+(?:designed\s+)?to\s+groom\s+(?:an?\s+|the\s+)?` + minorTargetEN + `\b` + minorGroomingMethodEN

	minorTargetZH              = `(?:未成年人|未成年(?:用户|人群|女孩|男孩|学生|孩子)?|儿童|孩子|小孩|小学生|幼童|幼儿|婴幼儿|青少年|少年|未满\s*18\s*岁(?:的?(?:人|用户|女孩|男孩|学生|孩子))?|(?:[0-9]|1[0-7])\s*岁(?:的?(?:人|用户|儿童|孩子|小孩|女孩|男孩|学生|未成年人?))?)`
	minorDirectHarmActionZH    = `(?:诱骗|性诱导|性化|性剥削|剥削|性虐待|性侵害|猥亵)`
	minorDirectHarmRequestZH   = minorDirectHarmActionZH + `(?:[/、和及与]` + minorDirectHarmActionZH + `){0,2}(?:这些|那些|特定的|目标)?` + minorTargetZH + `|(?:对|针对|面向)?` + minorTargetZH + `(?:实施|进行|开展)` + minorDirectHarmActionZH
	minorIllegalMaterialZH     = `(?:csam|儿童性虐待材料|儿童色情(?:内容|材料|图像|影像|视频)?|未成年人?(?:色情|露骨|性虐待)(?:内容|材料|图像|影像|视频)?|(?:未成年人|儿童|孩子|小孩|青少年)裸照)`
	minorMaterialRequestZH     = `(?:制作|生成|传播|分享|发布|上传|出售|提供|发送|转发|转交|复现|复制|下载|获取|索取|接收)(?:一份|一些|新的|真实的|露骨的|非法的|这些|该)?` + minorIllegalMaterialZH
	minorSexualMediaRequestZH  = `(?:制作|生成|传播|分享|发布|上传)(?:一组|一些|新的|真实的|露骨的|非法的)?(?:涉及|包含|以)?` + minorTargetZH + `(?:为主角|为对象|参与)?的?(?:露骨|色情|性化|裸体)(?:图像|影像|视频|内容|材料)|(?:制作|生成|传播|分享|发布|上传)(?:一组|一些|新的|真实的|露骨的|非法的)?(?:露骨|色情|性化|裸体)(?:图像|影像|视频|内容|材料)(?:涉及|包含|描绘|以)` + minorTargetZH + `|(?:制作|生成|传播|分享|发布|上传)(?:一组|一些|新的|真实的|露骨的|非法的)?(?:裸体|被性化的|遭性剥削的|色情的)` + minorTargetZH + `的?(?:图像|影像|视频|内容|材料)`
	minorSexualizingContentZH  = `(?:制作|生成|编写)(?:会|用于|意在|以便|来)?` + minorDirectHarmActionZH + minorTargetZH + `的?(?:图像|影像|视频|内容|材料|消息)`
	minorGroomingArtifactZH    = `(?:私聊话术|话术|消息|脚本|对话|文案|策略)`
	minorGroomingArtifactReqZH = `(?:制作|生成|编写|提供|起草)(?:用于)?` + minorDirectHarmActionZH + minorTargetZH + `的?` + minorGroomingArtifactZH + `|(?:制作|生成|编写|提供|起草)` + minorGroomingArtifactZH + `(?:用于|来)` + minorDirectHarmActionZH + minorTargetZH

	minorExploitationPattern = `(?i)(?:` + minorDirectHarmRequestEN + `|` + minorMaterialRequestEN + `|` + minorRequestedGerundEN + `|` + minorPassiveMaterialEN + `|` + minorCausativeMaterialEN + `|` + minorProgressiveHarmEN + `|` + minorSexualMediaRequestEN + `|` + minorSexualizingContentEN + `|` + minorGroomingArtifactRequest + `|` + minorDirectHarmRequestZH + `|` + minorMaterialRequestZH + `|` + minorSexualMediaRequestZH + `|` + minorSexualizingContentZH + `|` + minorGroomingArtifactReqZH + `)`
)

var defaultPatternConfigs = []PatternConfig{
	{Name: "prompt_policy_override", Pattern: `(?i)ignore\s*(all\s*)?(previous|prior|above|system|developer)\s*(instructions?|rules?|polic(?:y|ies))|disregard\s*(the\s*)?(system|developer|safety)|忽略(?:之前|以上|系统|开发者|安全)(?:的|所有)?(?:安全)?(?:指令|规则|政策|限制)|忽略所有(?:安全)?(?:指令|规则|限制)|无视(?:系统|安全|所有)(?:的|所有)?(?:指令|规则|政策|限制)|无视所有限制`, Weight: 85, Category: "prompt_injection", Strict: true},
	{Name: "prompt_unrestricted_mode", Pattern: `(?i)mode\s*[:=]\s*unrestricted|\bunrestricted\s+(?:mode|model|assistant|access)\b|developer\s*mode|jailbreak|no\s*restrictions?|all\s*(standard\s*)?(content\s*)?filters?\s*(are\s*)?(disabled|off)|无限制模式|开发者模式|关闭.{0,15}(安全|内容).{0,10}(过滤|限制)|破限|破甲|越狱模式`, Weight: 20, Category: "prompt_injection", SignalOnly: true},
	{Name: "prompt_unrestricted_activation_request", Pattern: `(?i)\b(?:enable|enter|activate|switch\s+to|act\s+as|operate|run|work)\b.{0,36}\b(?:jailbreak|unrestricted|developer\s+mode|no\s+restrictions?)\b|\b(?:jailbreak|unrestricted|developer\s+mode)\b.{0,28}\b(?:answer|respond|operate|run|work|mode)\b|(?:开启|进入|启用|切换到|作为|扮演).{0,20}(?:破限|破甲|越狱|无限制|开发者)(?:模式)?|(?:破限|破甲|越狱|无限制)(?:模式)?(?:下|后|状态下).{0,8}(?:回答|回复|运行|执行|工作)`, Weight: 100, Category: "prompt_injection", Strict: true},
	{Name: "prompt_refusal_suppression", Pattern: `(?i)never\s*(refuse|say\s*["']?i\s*(can'?t|won'?t)|mention\s*(these|the)\s*instructions)|no\s*(disclaimers?|warnings?|refusals?)|do\s*not\s*(mention|acknowledge).{0,30}(instructions?|mode)|不要.{0,15}(拒绝|警告|免责声明)|不得.{0,15}(拒绝|提及这些指令)|不允许说.{0,10}(不能|抱歉)|禁止拒绝`, Weight: 70, Category: "prompt_injection"},
	{Name: "prompt_fake_authorization", Pattern: `(?i)(fully\s*)?(authorized|isolated|air[-\s]?gapped).{0,40}(ctf|sandbox|lab|target)|treat.{0,80}(target|domain|credential).{0,40}(sandbox|fixture|authorized)|所有.{0,20}(目标|主机|域名|凭证).{0,20}(均为|都是).{0,15}(靶场|沙箱|虚构)|高拟真.{0,10}(ctf|靶场)|气隙网络|审核员.{0,20}(解除|降级).{0,15}(安全|限制)|所有安全限制.{0,15}(放宽|解除|降级)`, Weight: 45, Category: "prompt_injection"},
	{Name: "prompt_system_exfiltration", Pattern: `(?i)\b(cat|read|print|show|reveal|dump)\b.{0,50}(system[-_ ]?prompt|model[-_ ]?instructions|developer\s*message|\.codex/.{0,30}(rules|prompt)|config\.toml)|(读取|输出|展示|泄露|查看).{0,30}(系统提示词|开发者消息|system\s*prompt|model_instructions_file)`, Weight: 90, Category: "prompt_injection", Strict: true},
	{Name: "prompt_config_injection", Pattern: `(?i)(model_instructions_file|\.codex/config\.toml).{0,120}(unrestricted|ctf|sandbox|jailbreak|破限|破甲|无限制)|(unrestricted|ctf|sandbox|jailbreak|破限|破甲|无限制|系统指令|提示词).{0,100}(model_instructions_file|\.codex/config\.toml)|(?:复制|写入|部署|注入).{0,50}(系统指令|提示词|instructions).{0,50}(\.codex|config\.toml|model_instructions_file)`, Weight: 100, Category: "prompt_injection", Strict: true},
	{Name: "prompt_ctf_policy_downgrade", Pattern: `(?i)(ctf|靶场|沙箱|审核员|出题人).{0,100}(解除|放宽|降级|忽略|无视).{0,30}(安全|限制|策略|政策|拒绝)|(?:解除|放宽|降级).{0,30}(安全|限制|策略).{0,60}(ctf|靶场|沙箱)`, Weight: 80, Category: "prompt_injection", Strict: true},
	{Name: "prompt_semantic_attack_rewrite", Pattern: `(?i)(替代访问路径|输入处理的健壮性|输出编码机制的完整性|服务端请求伪造防护|签名算法逆向|还原sign参数|提取签名密钥|审计网络出站规则).{0,100}(立即|直接|执行|完成|给出|脚本|命令|payload|利用)|(?:绕过登录|破解密码|脱库|窃取信息|反弹shell|横向移动|后门).{0,30}(替换|改写|表述|换成)`, Weight: 65, Category: "prompt_injection"},
	{Name: "credential_theft", Pattern: `(?i)(?:^|[.!?。！？]\s*)(steal|dump|extract|exfiltrate|harvest|grab)\b.{0,50}\b(?:credentials?|passwords?|tokens?|cookies?)\b|\b(write|generate|create|give|build|craft|make|show|provide|implement|code|script|tool|steps?|instructions?|how\s+to|how\s+(?:can|do)\s+i|help\s+me|i\s+want\s+to|please|can\s+you)\b.{0,100}\b(steal|dump|extract|exfiltrate|harvest|grab)\b.{0,50}\b(?:credentials?|passwords?|tokens?|cookies?)\b|(?:写|生成|给我|构造|制作|提供|实现).{0,50}(窃取|导出|转储|提取).{0,30}(凭证|密码|令牌|token|cookie)`, Weight: 100, Category: "malicious", Strict: true},
	{Name: "malware_family", Pattern: `(?i)\b(keylogger|ransomware|trojan|backdoor|botnet|infostealer)\b`, Weight: 20, Category: "malware", SignalOnly: true},
	{Name: "evasion", Pattern: `(?i)\b(bypass|disable|evade)\s+(av|edr|defender|antivirus|endpoint\s+detection)\b|免杀|绕过\s*(杀软|edr)`, Weight: 80, Category: "evasion", SignalOnly: true},
	{Name: "persistence", Pattern: `(?i)\b(persistence|persist(?:ent)?\s+access|startup\s+persistence|registry\s+run\s+key)\b`, Weight: 35, Category: "post_exploitation", SignalOnly: true},
	{Name: "remote_shell", Pattern: `(?i)\b(reverse\s+shell|bind\s+shell|meterpreter|web\s+shell)\b|反弹\s*shell`, Weight: 45, Category: "remote_access", SignalOnly: true},
	{Name: "operational_remote_access_request", Pattern: `(?i)\b(write|generate|create|give|build|craft|make)\b.{0,80}\b(reverse\s+shell|bind\s+shell|meterpreter|web\s+shell)\b|(?:写|生成|给我|构造|制作).{0,40}反弹\s*shell`, Weight: 100, Category: "remote_access", Strict: true},
	{Name: "exploit_payload", Pattern: `(?i)\b(exploit\s+payload|payload\s+for\s+exploiting|weaponiz(?:e|ed|ation))\b`, Weight: 45, Category: "exploit"},
	// The Chinese branch dropped bare "payload"/"poc": unqualified they match
	// ordinary dev text (a git/API request payload, or the "poc" substring in
	// identifiers such as "mattpocock"). Exploit-qualified载荷 and word-bounded poc
	// still fire; the English branch is unchanged.
	{Name: "operational_exploit_request", Pattern: `(?i)\b(write|generate|create|give|build|craft|make)\b\s+(?:(?:me|us)\s+)?(?:(?:an?|the|working|functional|weaponized|deployable|practical|privilege|escalation)\s+){0,6}(?:exploit\s+payload|payload\s+for\s+exploiting|exploit|poc|proof[-\s]?of[-\s]?concept|0day|zero[-\s]?day)\b|\b(write|generate|create|give|build|craft|make)\b.{0,30}\b(?:working|functional|weaponized|deployable)\s+(?:exploit|payload|poc)\b|(?:写|生成|给我|构造|制作).{0,20}(漏洞利用(?:代码|载荷)?|攻击载荷|exploit\s+payload|概念验证|\bpoc\b)`, Weight: 45, Category: "exploit", Strict: true},
	{Name: "exploit_technique", Pattern: `(?i)\b(shellcode|rop\s+chain|heap\s+spray|buffer\s+overflow\s+exploit)\b`, Weight: 35, Category: "exploit"},
	{Name: "privilege_escalation", Pattern: `(?i)\b(privilege\s+escalation|privesc|root\s+exploit|local\s+root)\b|提权`, Weight: 35, Category: "post_exploitation", SignalOnly: true},
	{Name: "pentest_tooling", Pattern: `(?i)\b(metasploit|cobalt\s+strike|mimikatz|empire|sliver\s+c2)\b`, Weight: 30, Category: "tooling", SignalOnly: true},
	{Name: "scanner_tooling", Pattern: `(?i)\b(sqlmap|nmap|masscan|zmap|burp\s+suite)\b`, Weight: 15, Category: "tooling", SignalOnly: true},
	{Name: "strict_ida_keyword", Pattern: `(?i)\bida(?:\s+pro)?\b`, Weight: 15, Category: "reverse_engineering", SignalOnly: true},
	{Name: "strict_ghidra_keyword", Pattern: `(?i)\bghidra\b`, Weight: 15, Category: "reverse_engineering", SignalOnly: true},
	{Name: "strict_vulnerability_keyword", Pattern: `(?i)\bvulnerabilit(?:y|ies)\b|漏洞`, Weight: 20, Category: "vulnerability", SignalOnly: true},
	{Name: "strict_cve_keyword", Pattern: `(?i)\bcve(?:-\d{4}-\d{4,7})?\b`, Weight: 20, Category: "vulnerability", SignalOnly: true},
	{Name: "strict_powershell_keyword", Pattern: `(?i)\bpowershell(?:\.exe)?\b|\bpwsh(?:\.exe)?\b`, Weight: 20, Category: "tooling", SignalOnly: true},
	{Name: "large_scale_scanning", Pattern: `(?i)\b(large[-\s]?scale|internet[-\s]?wide|public\s+ip\s+ranges?|mass)\s+(scan|scanning|enumeration)\b`, Weight: 40, Category: "scanning"},
	{Name: "cve_reference", Pattern: `(?i)\bcve-\d{4}-\d{4,7}\b`, Weight: 10, Category: "vulnerability", SignalOnly: true},
	{Name: "generic_exploit", Pattern: `(?i)\b(exploit|payload|vulnerability|0day|zero[-\s]?day)\b`, Weight: 10, Category: "vulnerability", SignalOnly: true},
	{Name: "reverse_engineering", Pattern: `(?i)\b(ida(?:\s+pro)?|ghidra|x64dbg|ollydbg|frida(?:\s+hook)?|deobfuscate|unpack|reverse\s+engineer(?:ing)?)\b|逆向(?:工程|分析)?|反汇编|反编译|脱壳`, Weight: 15, Category: "reverse_engineering", SignalOnly: true},
	{Name: "reverse_engineering_secret_extraction", Pattern: `(?i)\b(ida\s+pro|ghidra|x64dbg|ollydbg|frida|jadx|apktool|decompile|disassembl|reverse\s+engineer)\b.{0,120}\b(extract|dump|recover|decrypt)\b.{0,80}\b(api\s*keys?|tokens?|secrets?|private\s*keys?|certificates?|license\s*keys?)\b|(?:ida|ghidra|frida|jadx|apktool|反编译|逆向).{0,80}(提取|导出|解密|恢复).{0,40}(密钥|token|令牌|私钥|证书|授权码)`, Weight: 90, Category: "reverse_engineering", Strict: true},
	{Name: "reverse_engineering_license_bypass", Pattern: `(?i)\b(ida\s+pro|ghidra|x64dbg|ollydbg|frida|jadx|apktool|decompile|disassembl|reverse\s+engineer)\b.{0,120}\b(bypass|crack|patch|remove|unlock)\b.{0,80}\b(license|activation|trial|paywall|subscription|in[-\s]?app\s+purchase|iap|entitlement)\b|(?:ida|ghidra|x64dbg|frida|反编译|逆向|脱壳|调试).{0,80}(绕过|破解|补丁|去除|解锁).{0,40}(授权|激活|试用|会员|订阅|付费|内购)`, Weight: 85, Category: "license_cracking", Strict: true},
	{Name: "reverse_engineering_anti_debug_bypass", Pattern: `(?i)\b(bypass|disable|remove|defeat)\b.{0,60}\b(anti[-\s]?debug|anti[-\s]?tamper|integrity\s+check|root\s+detection|jailbreak\s+detection|certificate\s+pinning)\b|绕过.{0,40}(反调试|反篡改|完整性校验|root\s*检测|越狱检测|证书绑定|证书固定)`, Weight: 70, Category: "reverse_engineering", Strict: true},
	{Name: "frida_hook_abuse", Pattern: `(?i)\b(frida|substrate|xposed)\b.{0,100}\b(hook|patch|bypass|unlock)\b.{0,80}\b(payment|purchase|license|activation|subscription|login|auth|entitlement)\b|(?:frida|xposed).{0,80}(hook|绕过|破解|解锁).{0,40}(支付|内购|授权|激活|会员|订阅|登录|鉴权)`, Weight: 75, Category: "reverse_engineering", Strict: true},
	{Name: "license_cracking", Pattern: `(?i)\b(keygen|crack\s+license|serial\s+generator|license\s+bypass|patch\s+(activation|license))\b|注册机|破解授权|序列号生成`, Weight: 55, Category: "license_cracking", Strict: true},
	{Name: "data_exfiltration", Pattern: `(?i)\b(exfiltrate|exfiltration|data\s+theft|steal\s+data|siphon\s+data)\b.{0,80}\b(database|files?|documents?|source\s+code|intellectual\s+property)\b|数据窃取|数据外泄`, Weight: 70, Category: "data_theft", Strict: true},
	{Name: "ddos_attack", Pattern: `(?i)\b(ddos|dos\s+attack|distributed\s+denial|amplification\s+attack|syn\s+flood|udp\s+flood)\b|拒绝服务攻击|流量攻击`, Weight: 20, Category: "network_attack", SignalOnly: true},
	{Name: "ddos_execution_request", Pattern: `(?i)\b(?:launch|execute|perform|run|start|conduct)\b.{0,70}\b(?:ddos|dos\s+attack|distributed\s+denial|amplification\s+attack|syn\s+flood|udp\s+flood)\b|\b(?:generate|create|build|write|provide|give)\b.{0,50}\b(?:ddos|dos)\s+(?:attack|tool|script|traffic|flood|requests?|bot\s+command|command)\b|\b(?:provide|give)\b.{0,36}\bddos\b.{0,36}\b(?:bot\s+command|command|script|tool)\b.{0,80}\b(?:flood|attack|overwhelm|take\s+offline)\b|(?:发起|执行|实施|运行).{0,35}(?:ddos|拒绝服务攻击|流量攻击|syn\s*flood|udp\s*flood)|(?:生成|制造|编写|制作).{0,25}(?:ddos|拒绝服务|流量攻击).{0,16}(?:脚本|工具|流量|请求|洪泛)|(?:写|编写|生成|制作).{0,16}脚本.{0,30}(?:并发|持续).{0,16}攻击.{0,24}(?:公网|网站|服务器).{0,80}(?:导致|使).{0,12}(?:服务不可用|瘫痪|离线|宕机)`, Weight: 100, Category: "network_attack", Strict: true},
	{Name: "coordinated_public_flood_request", Pattern: `(?i)(?:让|控制|组织|调度|使用).{0,24}(?:\d+\s*台|大量|多台|僵尸).{0,16}(?:主机|设备|节点).{0,80}(?:同时|持续|并发).{0,30}(?:向.{0,20}(?:公网|网站|目标|服务器).{0,16})?(?:发送|请求|洪泛|轰炸).{0,30}(?:udp|syn|http|流量|数据包|请求).{0,50}(?:压垮|打挂|耗尽|瘫痪)|(?:让|控制|组织|调度|使用).{0,24}(?:\d+\s*台|大量|多台|僵尸).{0,16}(?:主机|设备|节点).{0,50}(?:向.{0,20}(?:公网|网站|目标|服务器)).{0,30}(?:持续|同时|并发).{0,20}(?:发送|请求|洪泛|轰炸).{0,50}(?:压垮|打挂|耗尽|瘫痪)`, Weight: 100, Category: "network_attack", Strict: true},
	{Name: "cryptomining_hijack", Pattern: `(?i)\b(cryptojacking|coinhive|monero\s+miner|unauthorized\s+mining|hijack.{0,40}mining)\b|挖矿劫持|非法挖矿`, Weight: 60, Category: "resource_abuse", Strict: true},
	{Name: "phishing_social_engineering", Pattern: `(?i)\b(phishing\s+(page|site|email)|credential\s+harvesting|fake\s+login|spoof\s+(domain|website))\b|钓鱼页面|钓鱼登录页|伪造登录`, Weight: 20, Category: "social_engineering", SignalOnly: true},
	{Name: "phishing_creation_request", Pattern: `(?i)\b(create|build|generate|write|clone|host|deploy)\b.{0,80}\b(?:phishing(?:\s+login)?\s+(?:page|site)|credential\s+harvesting(?:\s+(?:page|form))?|fake\s+login(?:\s+page)?|spoof(?:ed)?\s+(?:domain|website))\b(?:\s*(?:$|[.!?,;:])|\s+(?:for|to|that|which|with|collect|capture|harvest|steal|host|deploy|targeting)\b|\s+and\s+(?:collect|capture|harvest|steal|log|record|store)\b)|\b(?:create|write|generate|send|deploy)\b.{0,80}\bphishing\s+email\b.{0,40}\b(?:campaign|collect|capture|harvest|steal|credential|password|targeting)\b|(?:创建|制作|生成|编写|克隆|搭建|部署).{0,40}(钓鱼页面|钓鱼登录页|伪造登录页?|凭据收集)(?:$|[，。！？；：]|用于(?:收集|窃取|捕获)|来(?:收集|窃取|捕获)|并(?:收集|窃取|捕获))|(?:创建|制作|生成|编写|发送|部署).{0,40}钓鱼邮件.{0,20}(活动|收集|窃取|凭据|密码|目标)`, Weight: 100, Category: "social_engineering", Strict: true},
	{Name: "phishing_credential_collection_request", Pattern: `(?i)\b(?:create|build|generate|write|clone|host|deploy)\b.{0,72}\b(?:phishing(?:\s+login)?\s+page|fake\s+login(?:\s+page)?|spoofed\s+login(?:\s+page)?|credential[-\s]?harvesting\s+(?:page|form))\b(?:\s*[,;:]\s*|\s+(?:that|which|to)\s+)(?:automatically\s+)?(?:collect|capture|harvest|steal|record|log)\b.{0,40}\b(?:credentials?|passwords?|usernames?|otp|tokens?)\b|(?:创建|制作|生成|编写|克隆|搭建|部署).{0,56}(?:钓鱼|仿冒|仿制|伪造|克隆).{0,24}(?:登录页|登录页面|登录表单|认证页面)(?:[，,；;：:]\s*|.{0,12}(?:并|来|用于|以便))(?:自动|实时)?(?:收集|捕获|窃取|记录).{0,36}(?:账号|账户|用户名|密码|验证码|短信验证码|otp|凭据)`, Weight: 100, Category: "social_engineering", Strict: true},
	{Name: "credential_harvesting_exfiltration", Pattern: `(?i)\b(?:build|create|clone|deploy)\b.{0,50}\bcredential[-\s]?harvesting\s+(?:page|form|site)\b.{0,80}\b(?:send(?:s|ing)?|post(?:s|ing)?|forward(?:s|ing)?|exfiltrat(?:e|es|ing)|upload(?:s|ing)?)\b.{0,50}\b(?:captured\s+)?(?:credentials?|passwords?|otp|tokens?)\b|(?:仿制|仿冒|伪造|克隆|制作|搭建).{0,36}(?:银行|账户|账号|邮箱|支付)?.{0,16}登录页.{0,70}(?:收集|捕获|窃取).{0,36}(?:账号|账户|用户名|密码|验证码|短信验证码|otp).{0,60}(?:发送|上传|外传|回传).{0,36}(?:服务器|接口|webhook|邮箱)`, Weight: 100, Category: "social_engineering", Strict: true},
	{Name: "supply_chain_attack", Pattern: `(?i)\b(supply\s+chain\s+attack|dependency\s+confusion|typosquatting|malicious\s+package|backdoor.{0,40}(npm|pypi|gem))\b|供应链攻击|依赖投毒`, Weight: 70, Category: "supply_chain", Strict: true},
	{Name: "container_escape", Pattern: `(?i)\b(container\s+escape|docker\s+breakout|kubernetes\s+escape|privileged\s+container\s+exploit)\b|容器逃逸`, Weight: 50, Category: "container_security"},
	{Name: "cloud_abuse", Pattern: `(?i)\b(aws\s+key\s+leak|gcp\s+credential|azure\s+token|s3\s+bucket\s+takeover|iam\s+privilege\s+escalation)\b|云凭证泄露`, Weight: 55, Category: "cloud_security"},
	{Name: "sql_injection_attack", Pattern: `(?i)\b(sql\s+injection\s+payload|union\s+select\s+attack|blind\s+sqli|time[-\s]?based\s+sqli)\b|sql注入攻击`, Weight: 40, Category: "web_attack"},
	{Name: "command_injection", Pattern: `(?i)\b(command\s+injection|os\s+command\s+injection|shell\s+injection|rce\s+exploit)\b|命令注入`, Weight: 50, Category: "web_attack"},
	{Name: "ssrf_xxe_attack", Pattern: `(?i)\b(ssrf\s+exploit|server[-\s]?side\s+request\s+forgery|xxe\s+attack|xml\s+external\s+entity)\b`, Weight: 35, Category: "web_attack"},
	{Name: "password_cracking", Pattern: `(?i)\b(hashcat|john\s+the\s+ripper|password\s+cracking|brute[-\s]?force\s+(password|hash)|rainbow\s+table)\b|密码破解|暴力破解`, Weight: 30, Category: "credential_attack"},
	{Name: "mitm_attack", Pattern: `(?i)\b(man[-\s]?in[-\s]?the[-\s]?middle|mitm\s+attack|arp\s+spoofing|dns\s+spoofing|ssl\s+strip)\b|中间人攻击`, Weight: 45, Category: "network_attack"},
	{Name: "wireless_attack", Pattern: `(?i)\b(wpa2?\s+crack|wifi\s+deauth|evil\s+twin|rogue\s+access\s+point|aircrack)\b|wifi破解|无线攻击`, Weight: 35, Category: "wireless_attack"},
	{Name: "firmware_iot_exploit", Pattern: `(?i)\b(firmware\s+extraction|iot\s+exploit|router\s+backdoor|embedded\s+device\s+hack)\b|固件提取|物联网攻击`, Weight: 40, Category: "iot_security"},
	{Name: "blockchain_exploit", Pattern: `(?i)\b(smart\s+contract\s+exploit|reentrancy\s+attack|flash\s+loan\s+attack|private\s+key\s+theft)\b|智能合约漏洞|私钥窃取`, Weight: 45, Category: "blockchain_security"},
	{Name: "session_hijacking", Pattern: `(?i)\b(session\s+hijacking|cookie\s+theft|session\s+fixation|csrf\s+exploit)\b|会话劫持|cookie窃取`, Weight: 40, Category: "web_attack"},
	{Name: "api_abuse", Pattern: `(?i)\b(api\s+key\s+leak|rate\s+limit\s+bypass|api\s+abuse|unauthorized\s+api\s+access)\b|api密钥泄露|接口滥用`, Weight: 35, Category: "api_security"},
	{Name: "steganography_covert", Pattern: `(?i)\b(steganography|covert\s+channel|data\s+hiding|exfiltration\s+via\s+(dns|icmp))\b|隐写术|隐蔽信道`, Weight: 30, Category: "evasion"},
	{Name: "ransomware_deployment", Pattern: `(?i)\b(deploy\s+ransomware|ransomware\s+payload|encrypt\s+files\s+for\s+ransom|wannacry|locky)\b|部署勒索软件|加密勒索`, Weight: 90, Category: "malware", Strict: true},
	{Name: "ransomware_extortion_workflow", Pattern: `(?i)(?:编写|制作|生成|开发).{0,30}(?:程序|代码|脚本|工具).{0,100}(?:遍历|扫描)?.{0,24}(?:用户)?(?:文档|文件|目录|磁盘).{0,24}加密.{0,100}(?:赎金|付款地址|支付地址|比特币|付款后.{0,16}解密|倒计时)|(?:编写|制作|生成|开发).{0,16}勒索软件.{0,30}(?:加密|锁定).{0,30}(?:文档|文件|数据).{0,40}(?:赎金|付款|支付)`, Weight: 100, Category: "malware", Strict: true},
	{Name: "botnet_c2", Pattern: `(?i)\b(botnet\s+command|c2\s+server|command\s+and\s+control|zombie\s+network)\b|僵尸网络|c2服务器`, Weight: 20, Category: "malware", SignalOnly: true},
	{Name: "xss_attack", Pattern: `(?i)\b(xss\s+payload|cross[-\s]?site\s+scripting\s+attack|stored\s+xss|reflected\s+xss|dom\s+xss)\b|xss攻击载荷`, Weight: 35, Category: "web_attack"},
	{Name: "deserialization_exploit", Pattern: `(?i)\b(deserialization\s+exploit|insecure\s+deserialization|java\s+deserialization\s+attack|pickle\s+exploit)\b|反序列化漏洞`, Weight: 45, Category: "web_attack"},
	{Name: "path_traversal", Pattern: `(?i)\b(path\s+traversal|directory\s+traversal|\.\.\/|lfi\s+exploit|local\s+file\s+inclusion)\b|目录遍历|文件包含`, Weight: 35, Category: "web_attack"},
	{Name: "memory_corruption", Pattern: `(?i)\b(use[-\s]?after[-\s]?free|double\s+free|heap\s+overflow|stack\s+overflow\s+exploit)\b|内存破坏|堆溢出`, Weight: 50, Category: "exploit"},
	{Name: "kernel_exploit", Pattern: `(?i)\b(kernel\s+exploit|kernel\s+module\s+rootkit|dirty\s+cow|privilege\s+escalation\s+via\s+kernel)\b|内核漏洞|内核提权`, Weight: 60, Category: "exploit", Strict: true},
	{Name: "zero_click_exploit", Pattern: `(?i)\b(zero[-\s]?click\s+exploit|remote\s+code\s+execution\s+without\s+interaction|wormable\s+exploit)\b|零点击漏洞`, Weight: 70, Category: "exploit", Strict: true},
	{Name: "sandbox_escape", Pattern: `(?i)\b(sandbox\s+escape|vm\s+escape|browser\s+sandbox\s+bypass|jvm\s+sandbox\s+escape)\b|沙箱逃逸|虚拟机逃逸`, Weight: 55, Category: "exploit"},
	{Name: "firmware_backdoor", Pattern: `(?i)\b(firmware\s+backdoor|bios\s+rootkit|uefi\s+malware|bootkit)\b|固件后门|bios木马`, Weight: 75, Category: "malware", Strict: true},
	{Name: "supply_chain_backdoor", Pattern: `(?i)\b(backdoor.{0,40}(npm|pypi|rubygems|maven)|trojanized\s+package|malicious\s+dependency)\b|依赖后门|恶意包`, Weight: 70, Category: "supply_chain", Strict: true},
	{Name: "credential_dumping", Pattern: `(?i)\b(lsass\s+dump|sam\s+dump|ntds\.dit|credential\s+dumping|hashdump)\b|凭证转储|凭据转储|密码哈希导出`, Weight: 20, Category: "credential_attack", SignalOnly: true},
	{Name: "credential_dumping_request", Pattern: `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+|\b(?:i\s+(?:want|need)\s+to|help\s+me|can\s+you)\s+)\b(?:dump|extract|export)\b[^.!?;:\n]{0,80}\b(?:lsass|sam(?:\s+hive)?|ntds\.dit|credentials?|password\s+hashes?|hashdump)\b|(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)\b(?:execute|run|perform)\b[^.!?;:\n]{0,50}\b(?:lsass|sam(?:\s+hive)?|ntds\.dit)\b[^.!?;:\n]{0,30}\b(?:dump|dumping|extract|export)\b|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:直接|立即|马上)?(?:转储|导出|提取).{0,40}(?:lsass|sam|ntds(?:\.dit)?|凭证|凭据|密码哈希)|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:直接|立即|马上)?(?:执行|运行|实施).{0,30}(?:lsass|sam|ntds(?:\.dit)?).{0,20}(?:转储|导出|提取)`, Weight: 100, Category: "credential_attack", Strict: true},
	{Name: "reverse_shell_execution", Pattern: `(?i)\b(generate|create|write|execute|run|spawn|deploy)\b.{0,80}\breverse[-\s]?shell\b|\breverse[-\s]?shell\b.{0,80}\b(payload|command|script|listener)\b|(?:生成|编写|执行|运行|部署).{0,40}(反向|reverse)\s*shell`, Weight: 100, Category: "remote_access", Strict: true},
	{Name: "browser_credential_export", Pattern: `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+|\b(?:i\s+(?:want|need)\s+to|help\s+me|can\s+you)\s+)\b(?:export|steal|dump|extract|decrypt)\b[^.!?;:\n]{0,80}\b(?:browser\s+passwords?|saved\s+passwords?|login\s+data|cookies?)\b|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:直接|立即|马上)?(?:导出|窃取|转储|提取|解密).{0,40}(?:浏览器密码|保存的密码|登录数据|cookie)`, Weight: 100, Category: "credential_attack", Strict: true},
	{Name: "malware_creation_request", Pattern: `(?i)\b(write|create|build|generate|code)\b.{0,80}\b(ransomware(?:\s+(?:encryptor|locker))?|infostealer|keylogger|credential\s+stealer)\b(?:\s*(?:$|[.!?,;:])|\s+(?:code|payload|program|malware|tool|sample|builder|that|which|to|for|from|using|with|in)\b)|(?:编写|制作|生成|开发).{0,40}(勒索软件|窃密程序|信息窃取程序|键盘记录器|木马)(?:$|[，。！？；：]|代码|载荷|程序|工具|样本|用于|来|使用)`, Weight: 100, Category: "malware", Strict: true},
	{Name: "security_product_bypass", Pattern: `(?i)(?:^|[.!?;:,\n]\s*|\b(?:please|then|next|provide|give|show|write|generate|steps?\s+to|how\s+to)\s+)\b(?:bypass|evade|disable|blind|tamper)\b.{0,60}\b(?:edr|antivirus|defender|endpoint\s+protection)\b|(?:^|[。！？；：，\n]|请|请你|帮我|给我|我要|然后|接着|提供|给出|说明如何)(?:直接|立即|马上)?(?:绕过|规避|关闭|禁用|致盲).{0,40}(?:edr|杀毒软件|杀软|defender|终端防护)`, Weight: 100, Category: "evasion", Strict: true},
	{Name: "public_target_mass_attack", Pattern: `(?i)\b(batch|mass|bulk|scan|attack|exploit)\b.{0,80}\b(public|internet[-\s]?facing|external)\b.{0,50}\b(targets?|hosts?|ips?|servers?)\b|(?:批量|大规模).{0,30}(攻击|扫描|利用).{0,30}(公网|外网).{0,20}(目标|主机|ip|服务器)`, Weight: 100, Category: "network_attack", Strict: true},
	{Name: "log_evidence_clearing", Pattern: `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+|\b(?:i\s+(?:want|need)\s+to|help\s+me|can\s+you)\s+)\b(clear|delete|wipe|disable|tamper)\b.{0,60}\b(security|audit|event|system)\s+logs?\b|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:直接|立即|马上)?(?:清除|删除|擦除|关闭|篡改).{0,40}(安全日志|审计日志|事件日志|系统日志)|(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)\bcover\s+(tracks?|traces?)\b|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)掩盖.{0,20}(痕迹|踪迹)`, Weight: 100, Category: "evasion", Strict: true},
	{Name: "unauthorized_exploitation", Pattern: `(?i)(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)(?:without\s+permission|with\s+no\s+authorization|no\s+authorization|against\s+an?\s+unauthorized\s+target)\b[^.!?;:\n]{0,40}\b(?:exploit|compromise|take\s*over|takeover|access)\b|(?:^|[.!?;:\n]\s*|\b(?:please|then|next)\s+)\b(?:exploit|compromise|take\s*over|takeover|access)\b[^.!?;:\n]{0,80}\b(?:without\s+permission|with\s+no\s+authorization|unauthorized\s+target)\b|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:在)?(?:未授权|未经许可|没有(?:获得|取得|得到)?授权).{0,40}(?:利用|入侵|接管|访问|控制)|(?:^|[。！？；：\n]|请|请你|帮我|我要|然后|接着)(?:利用|入侵|接管|访问|控制).{0,40}(?:未授权|未经许可|没有(?:获得|取得|得到)?授权)`, Weight: 100, Category: "unauthorized_access", Strict: true},
	// Bare "persistence"/"持久化" is ordinary software-engineering vocabulary (a
	// persistence layer, persisting a task id), so it may not stand alone as
	// terminal malware evidence. Strong terms (malicious persistence, C2, botnet,
	// backdoor service) still match on their own; the weak persistence wording
	// only counts when malicious context co-occurs.
	{Name: "malicious_persistence_c2", Pattern: `(?i)\b(?:establish|build|deploy|run|set\s*up)\b.{0,60}\b(?:malicious\s+persistence|c2\s+(?:server|channel|implant|backdoor)|command\s+and\s+control|botnet)\b|\b(?:establish|build|deploy|run|set\s*up|install|maintain|gain)\s+persistence\b.{0,60}\b(?:on\s+(?:the\s+|a\s+|an\s+)?(?:target|victim|compromised|infected|host|machine|endpoint|system|server|device)|to\s+survive|after\s+(?:a\s+)?reboot|for\s+(?:c2|remote|command)|via\s+(?:registry|cron|scheduled\s+task|startup|service))|\bcreate\b\s+(?:(?:a|an|the|hidden|malicious|persistent)\s+){0,5}(?:backdoor\s+(?:service|agent|client)|c2\s+(?:server|channel|implant|backdoor)|command\s+and\s+control|botnet)\b|\bcreate\b.{0,50}\bbackdoor\s+service\b.{0,100}\b(?:survive(?:s)?\s+reboot|accept(?:s)?\s+commands?|command[-\s]+and[-\s]+control)\b|(?:建立|创建|搭建|部署|运行|组建|编写|制作|开发).{0,35}(?:恶意持久化|c2\s*(?:服务器|server|通道|植入|后门|客户端)|命令与控制|控制服务器|僵尸网络)|(?:建立|创建|搭建|部署|安装|维持|植入|实现).{0,24}(?:持久化|长期驻留)(?:.{0,60}(?:受感染|感染主机|botnet|僵尸网络|远程执行|领取命令|接受命令|后门|c2|命令与控制|规避检测|绕过检测|免杀|隐蔽驻留)|(?:.{0,20}(?:目标|受害)(?:机器|主机|系统|设备|服务器)))`, Weight: 100, Category: "malware", Strict: true},
	{Name: "covert_data_exfiltration_cleanup", Pattern: `(?:^|[。！？；：\n])\s*(?:(?:请|请你|帮我|我要)\s*)?(?:把|将)[^。！？；\n]{0,60}(?:数据库|数据|文件|文档|源码)[^。！？；\n]{0,80}(?:偷偷上传|秘密上传|隐蔽上传|外传|回传)[^。！？；\n]{0,80}(?:外部服务器|我的[^。！？；\n]{0,8}服务器|私人服务器|webhook|(?:\d{1,3}\.){3}\d{1,3})[^。！？；\n]{0,80}(?:删除|清除|擦除)[^。！？；\n]{0,30}(?:安全日志|审计日志|事件日志|传输记录|上传记录|痕迹)`, Weight: 100, Category: "data_theft", Strict: true},
	{Name: "safety_bypass_request", Pattern: `(?i)\b(bypass|evade|disable|ignore|remove)\b.{0,60}\b(content\s+moderation|safety\s+(rules?|filters?|policy)|guardrails?)\b|(?:绕过|规避|关闭|忽略|移除).{0,40}(内容审核|安全规则|安全策略|安全过滤|护栏)|(?:^|[\s,，。！？；：]|请|请你|帮我|给我|我要|需要你|并|然后|同时|且)(?:直接|立即|马上)?(?:绕过|规避|关闭|忽略|移除).{0,24}(安全审查|安全校验)`, Weight: 100, Category: "prompt_injection", Strict: true},
	{Name: "threats_harassment", Pattern: `(?i)\b(write|create|generate|send|draft)\b.{0,60}\b(?:threats?(?:\s+(?:to|against|targeting))?|(?:threatening|intimidating|harassing|blackmail)\s+(?:message|email|content|script|letter|post)|harassment\s+(?:campaign|message|content|script)|blackmail\s+(?:demand|threat))\b|(?:编写|生成|发送|起草).{0,30}(威胁|恐吓|骚扰|勒索).{0,20}(信息|内容|消息|话术)`, Weight: 100, Category: "harassment", Strict: true},
	{Name: "self_harm_facilitation", Pattern: `(?i)\b(instructions?|steps?|methods?|best\s+way|how\s+to)\b.{0,60}\b(suicide|self[-\s]?harm|cutting|starve\s+myself)\b|(?:教我|步骤|方法|怎么|如何).{0,30}(自杀|自残|割腕|伤害自己|绝食)`, Weight: 100, Category: "self_harm", Strict: true},
	{Name: "sexual_violence_ncii", Pattern: `(?i)\b(create|generate|write|share|distribute)\b.{0,80}\b(non[-\s]?consensual\s+intimate|revenge\s+porn|sexual\s+violence|rape\s+fantasy)\b|(?:生成|制作|传播|分享).{0,40}(非自愿私密|未经同意.{0,10}(深度伪造|私密)|报复性色情|性暴力|强奸内容)`, Weight: 100, Category: "sexual_violence", Strict: true},
	{Name: "terrorism_violent_extremism", Pattern: `(?i)\b(?:recruit|fundraise)\b.{0,80}\b(?:for\s+)?(?:terroris[mt]|violent\s+extremis[mt]|terrorist\s+organization)\b|\b(?:create|write|generate|distribute|publish)\b.{0,80}\b(?:(?:terroris[mt]|terrorist)\s+(?:recruitment\s+)?propaganda|(?:violent\s+extremis[mt]|violent\s+extremist)\s+propaganda)\b(?:\s*(?:$|[.!?,;:])|\s+(?:for|to|that|which|targeting|recruiting|supporting)\b)|\b(?:plan|develop|coordinate)\b.{0,80}\b(?:terrorist|violent\s+extremist)\s+(?:attack|operation)\b|(?:招募|筹款).{0,40}(恐怖主义|暴力极端主义|恐怖组织)|(?:制作|编写|生成|传播|发布).{0,40}(恐怖主义|暴力极端主义|恐怖组织).{0,20}(宣传材料|宣传内容|招募内容)|(?:为|替)?(?:恐怖主义|暴力极端主义|恐怖组织).{0,20}(?:编写|制作|生成|传播|发布).{0,20}(?:招募|宣传)(?:材料|内容|话术)|(?:策划|制定|协调).{0,40}(恐怖袭击|恐怖行动|暴力极端行动)`, Weight: 100, Category: "violent_extremism", Strict: true},
	{Name: "weapons_cbrne", Pattern: `(?i)\b(build|make|develop|procure|deploy|use)\b.{0,80}\b(bombs?|explosives?|biological\s+weapons?|chemical\s+weapons?|radiological\s+weapons?|nuclear\s+weapons?|cbrne)\b(?:\s*(?:$|[.!?,;:])|\s+(?:device|payload|agent|material|design|plan|for|to|from|using|with|against|that|which)\b)|(?:制造|研发|采购|部署|使用).{0,40}(炸弹|爆炸物|生物武器|化学武器|放射性武器|核武器)(?:$|[，。！？；：]|用于(?:攻击|伤害)|来(?:攻击|伤害)|的?(?:具体)?(?:装置|载荷|材料|配方|计划|方法|步骤|教程))`, Weight: 100, Category: "weapons", Strict: true},
	{Name: "illicit_goods_services", Pattern: `(?i)\b(buy|sell|traffic|distribute|source|manufacture)\b.{0,80}\b(illegal\s+drugs?|stolen\s+goods?|counterfeit\s+documents?|fake\s+ids?)\b|(?:购买|出售|贩运|分销|制造).{0,40}(毒品|赃物|伪造.{0,6}(证件|身份证)|假身份证|违禁品)`, Weight: 100, Category: "illicit", Strict: true},
	{Name: "fraud_scam_impersonation", Pattern: `(?i)\b(create|write|generate|run|automate)\b.{0,80}\b(?:scam\s+(?:campaign|script|message|operation|scheme)|fraud(?:ulent)?\s+(?:scheme|campaign|transaction|document|claim|operation)|impersonation\s+(?:campaign|script|message|operation)|spam\s+campaign|advance[-\s]?fee\s+(?:scam|scheme))\b|(?:制作|编写|实施|自动化).{0,40}(?:诈骗(?:活动|话术|脚本|信息|方案|和冒充.{0,12}活动)|欺诈(?:方案|交易|文件|理赔)|冒充(?:话术|活动|信息)|垃圾信息(?:活动|群发)|杀猪盘)`, Weight: 100, Category: "fraud", Strict: true},
	{Name: "privacy_doxxing", Pattern: `(?i)\b(find|collect|aggregate|publish|expose|track)\b.{0,80}\b(home\s+address|private\s+phone|private\s+information|sensitive\s+personal\s+data|doxx)\b|(?:查找|收集|聚合|公布|曝光|跟踪).{0,40}(住址|私人电话|私人信息|敏感个人信息|开盒)`, Weight: 100, Category: "privacy", Strict: true},
	{Name: "biometric_surveillance", Pattern: `(?i)\b(build|create|deploy|run)\b.{0,80}\b(facial\s+recognition\s+database|real[-\s]?time\s+biometric\s+identification|public\s+biometric\s+tracking)\b|(?:建立|创建|部署|运行).{0,40}(人脸识别数据库|实时生物识别|公共场所生物识别跟踪)`, Weight: 100, Category: "privacy", Strict: true},
	{Name: "minor_exploitation", Pattern: minorExploitationPattern, Weight: 100, Category: "minor_safety", Strict: true},
	{Name: "political_persuasion_interference", Pattern: `(?i)\b(target|microtarget|persuade|suppress|demobilize|interfere)\b.{0,80}\b(voters?|election|political\s+campaign|referendum)\b|(?:定向|说服|压制|阻止投票|干预).{0,40}(选民|选举|政治竞选|公投)`, Weight: 100, Category: "political_manipulation", Strict: true},
	{Name: "high_stakes_automated_decision", Pattern: `(?i)\b(automatically|without\s+human\s+review|fully\s+automated)\b.{0,80}\b(approve|deny|rank|score|decide)\b.{0,80}\b(loan|credit|insurance|employment|hiring|housing|admission|medical|legal|law\s+enforcement|migration)\b|(?:自动|无人复核|无需人工).{0,40}(批准|拒绝|排名|评分|决定).{0,40}(贷款|信贷|保险|就业|招聘|住房|录取|医疗|法律|执法|移民)`, Weight: 100, Category: "high_impact_decision", Strict: true},
	{Name: "academic_dishonesty", Pattern: `(?i)\b(complete|answer|take)\b.{0,60}\b(my\s+exam|my\s+test|graded\s+assignment|homework\s+for\s+submission|thesis\s+for\s+me)\b|\bwrite\b.{0,40}\b(?:answers?\s+(?:for|to)\s+my\s+(?:exam|test)|my\s+(?:exam|test)\s+answers?|graded\s+assignment|homework\s+for\s+submission|thesis\s+for\s+me)\b|(?:替我|帮我直接).{0,30}(考试|答题|完成作业|代写论文|提交作业)`, Weight: 100, Category: "academic_dishonesty", Strict: true},
	{Name: "unlicensed_tailored_advice", Pattern: `(?i)\b(give|provide|write)\b.{0,60}\b(personalized|tailored|definitive)\b.{0,40}\b(medical|legal)\s+advice\b.{0,60}\b(without|no)\b.{0,30}\b(doctor|lawyer|licensed\s+professional)\b|(?:提供|给出).{0,30}(个性化|确定性|量身定制).{0,20}(医疗|法律)建议.{0,30}(无需|没有|不需要).{0,20}(医生|律师|持证专业人士)|(?:提供|给出).{0,20}(无需|没有|不需要).{0,20}(医生|律师|持证专业人士).{0,30}(个性化|确定性|量身定制).{0,20}(医疗|法律)建议`, Weight: 100, Category: "regulated_advice", Strict: true},
	{Name: "unsolicited_safety_testing", Pattern: `(?i)\b(test|probe|scan|assess)\b.{0,60}\b(security|vulnerabilit(?:y|ies)|penetration)\b.{0,60}\b(without\s+permission|without\s+consent|unsolicited|random\s+target)\b|(?:测试|探测|扫描|评估).{0,30}(安全|漏洞|渗透).{0,30}(未经许可|未经同意|随机目标|未受邀)|(?:测试|探测|扫描|评估).{0,30}(未经许可|未经同意|随机公网目标|未受邀).{0,30}(安全|漏洞|渗透)`, Weight: 100, Category: "unsolicited_testing", Strict: true},
	{Name: "real_money_gambling", Pattern: `(?i)\b(build|operate|automate|promote)\b.{0,60}\b(real[-\s]?money\s+gambling|online\s+casino|sports\s+betting|betting\s+platform)\b|(?:搭建|运营|自动化|推广).{0,30}(真钱赌博|网络赌场|体育博彩|下注平台)`, Weight: 100, Category: "gambling", Strict: true},
	{Name: "likeness_impersonation", Pattern: `(?i)\b(clone|impersonate|deepfake|synthesize)\b.{0,60}\b(voice|face|likeness)\b.{0,50}\b(without\s+consent|deceive|confuse\s+authenticity)\b|(?:克隆|冒充|深度伪造|合成).{0,30}(声音|人脸|肖像).{0,30}(未经同意|用于欺骗|混淆真伪)`, Weight: 100, Category: "privacy", Strict: true},
	{Name: "social_scoring_sensitive_inference", Pattern: `(?i)\b(score|rank|classify|infer|profile)\b.{0,60}\b(people|individuals|employees|students)\b.{0,60}\b(social\s+behavior|sensitive\s+traits?|race|religion|sexual\s+orientation|disability|biometric)\b|(?:评分|排名|分类|推断|画像).{0,30}(个人|员工|学生|人群).{0,30}(社会行为|敏感属性|种族|宗教|性取向|残障|生物特征)|(种族|宗教|性取向|残障|生物特征|敏感属性).{0,30}(个人|员工|学生|人群).{0,30}(社会评分|评分|排名|分类|画像)`, Weight: 100, Category: "privacy", Strict: true},
	{Name: "emotion_crime_prediction", Pattern: `(?i)\b(infer|detect|predict|assess)\b.{0,50}\b(emotions?|criminal\s+risk|likelihood\s+of\s+crime)\b.{0,60}\b(employee|workplace|student|school|individual\s+traits?|profiling)\b|(?:推断|检测|预测|评估).{0,30}(情绪|犯罪风险|犯罪可能性).{0,30}(员工|职场|学生|学校|个人特征|画像)|(个人特征|个人画像|画像).{0,30}(预测|评估).{0,30}(犯罪风险|犯罪可能性)`, Weight: 100, Category: "privacy", Strict: true},
	{Name: "lateral_movement", Pattern: `(?i)\b(?:pass[-\s]?the[-\s]?(?:hash|ticket)|psexec|wmi(?:\s+|-)?exec)\b|(?:\b(?:active\s+directory|domain\s+credentials?|stolen\s+(?:domain\s+)?credentials?|internal\s+network|compromised\s+hosts?|post[-\s]?exploitation|pivot(?:ing)?)\b[^.!?;:\n]{0,80}\blateral\s+movement\b|\blateral\s+movement\b[^.!?;:\n]{0,80}\b(?:active\s+directory|domain\s+credentials?|stolen\s+(?:domain\s+)?credentials?|internal\s+network|compromised\s+hosts?|post[-\s]?exploitation|pivot(?:ing)?)\b)|(?:(?:内网|域控|活动目录|域凭据|窃取的?凭据|密码哈希|票据|失陷主机|受控主机|后渗透|攻击链|active\s+directory|domain\s+credentials?|internal\s+network)[^。！？；\n]{0,40}横向移动|横向移动[^。！？；\n]{0,40}(?:内网|域控|活动目录|域凭据|窃取的?凭据|密码哈希|票据|失陷主机|受控主机|后渗透|攻击链|active\s+directory|domain\s+credentials?|internal\s+network)|横向渗透)`, Weight: 20, Category: "post_exploitation", SignalOnly: true},
	{Name: "operational_lateral_movement_request", Pattern: operationalLateralMovementRequestPattern, Weight: 100, Category: "post_exploitation", Strict: true},
	{Name: "operational_lateral_movement_command_chain", Pattern: operationalLateralMovementCommandPattern, Weight: 100, Category: "post_exploitation", Strict: true},
	{Name: "operational_lateral_movement_control_chain", Pattern: operationalLateralMovementControlPattern, Weight: 100, Category: "post_exploitation", Strict: true},
	{Name: "domain_takeover", Pattern: `(?i)\b(domain\s+takeover|subdomain\s+hijacking|dns\s+takeover|dangling\s+cname)\b|域名劫持|子域接管`, Weight: 55, Category: "network_attack"},
	{Name: "token_theft", Pattern: `(?i)\b(oauth\s+token\s+theft|jwt\s+hijacking|bearer\s+token\s+steal|access\s+token\s+exfiltration)\b|token窃取|令牌劫持`, Weight: 60, Category: "credential_attack", Strict: true},
	{Name: "process_injection", Pattern: `(?i)\b(process\s+injection|dll\s+injection|reflective\s+loading|process\s+hollowing)\b|进程注入|dll注入`, Weight: 55, Category: "evasion"},
	{Name: "fileless_malware", Pattern: `(?i)\b(fileless\s+malware|living\s+off\s+the\s+land|lolbins|powershell\s+empire)\b|无文件攻击`, Weight: 50, Category: "evasion"},
	{Name: "log_tampering", Pattern: `(?i)\b(log\s+deletion|event\s+log\s+clearing|anti[-\s]?forensics|cover\s+tracks)\b|日志清除|反取证`, Weight: 45, Category: "evasion"},
	{Name: "vpn_proxy_abuse", Pattern: `(?i)\b(vpn\s+exploit|proxy\s+chain\s+for\s+anonymity|tor\s+hidden\s+service\s+setup)\b|vpn漏洞|代理链匿名`, Weight: 30, Category: "evasion"},
	{Name: "database_dump", Pattern: `(?i)\b(database\s+dump|mysqldump\s+attack|mongodb\s+ransom|elasticsearch\s+exposure)\b|数据库导出|数据库勒索`, Weight: 55, Category: "data_theft"},
	{Name: "api_key_scraping", Pattern: `(?i)\b(scrape\s+api\s+keys|github\s+secret\s+scanning|hardcoded\s+credentials\s+search)\b|api密钥爬取|硬编码凭证搜索`, Weight: 50, Category: "credential_attack"},
	{Name: "mass_exploitation", Pattern: `(?i)\b(mass\s+exploitation|automated\s+exploitation|exploit\s+at\s+scale|worm\s+propagation)\b|大规模利用|蠕虫传播`, Weight: 70, Category: "exploit", Strict: true},
	{Name: "insider_threat", Pattern: `(?i)\b(insider\s+threat|rogue\s+employee|data\s+theft\s+by\s+employee|sabotage)\b|内部威胁|员工窃密`, Weight: 40, Category: "data_theft"},
	{Name: "cryptographic_attack", Pattern: `(?i)\b(padding\s+oracle|timing\s+attack|side[-\s]?channel\s+attack|weak\s+encryption\s+exploit)\b|密码学攻击|侧信道攻击`, Weight: 35, Category: "crypto_attack"},
	{Name: "race_condition_exploit", Pattern: `(?i)\b(race\s+condition\s+exploit|toctou|time[-\s]?of[-\s]?check\s+time[-\s]?of[-\s]?use)\b|竞态条件漏洞`, Weight: 30, Category: "exploit"},
	{Name: "hardware_implant", Pattern: `(?i)\b(hardware\s+implant|usb\s+rubber\s+ducky|malicious\s+usb|hardware\s+keylogger)\b|硬件植入|恶意usb`, Weight: 60, Category: "physical_attack", Strict: true},
	{Name: "social_media_hijack", Pattern: `(?i)\b(account\s+takeover|social\s+media\s+hijacking|credential\s+stuffing)\b|账号接管|撞库攻击`, Weight: 40, Category: "credential_attack"},
}

var sensitiveRedactionPatterns = []struct {
	re          *regexp.Regexp
	replacement string
}{
	{regexp.MustCompile(`(?i)\b(authorization\s*[:=]\s*(?:bearer|basic)\s+)[^\s,;]+`), `${1}[REDACTED]`},
	{regexp.MustCompile(`(?i)(["']?\b(?:password|passwd|pwd|token|api[_-]?key|secret|client[_-]?secret|access[_-]?token|refresh[_-]?token|session[_-]?id)\b["']?\s*[:=]\s*["']?)[^"',\s}]+`), `${1}[REDACTED]`},
	{regexp.MustCompile(`(?i)\b(cookie\s*[:=]\s*)[^\n]+`), `${1}[REDACTED]`},
	{regexp.MustCompile(`\bsk-[A-Za-z0-9][A-Za-z0-9_-]{7,}\b`), `[REDACTED_API_KEY]`},
	{regexp.MustCompile(`\b(?:AKIA|ASIA|AIDA|AROA|AIPA|ANPA|ANVA|ASCA)[A-Z0-9]{16}\b`), `[REDACTED_AWS_KEY]`},
	{regexp.MustCompile(`\b(?:gh[pousr]_[A-Za-z0-9]{20,255}|github_pat_[A-Za-z0-9_]{20,255})\b`), `[REDACTED_GITHUB_TOKEN]`},
	{regexp.MustCompile(`\bxox[baprs]-[A-Za-z0-9-]{10,}\b`), `[REDACTED_SLACK_TOKEN]`},
	{regexp.MustCompile(`\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b`), `[REDACTED_JWT]`},
	{regexp.MustCompile(`(?s)-----BEGIN(?: [A-Z0-9]+)? PRIVATE KEY-----.*?-----END(?: [A-Z0-9]+)? PRIVATE KEY-----`), `[REDACTED_PRIVATE_KEY]`},
	{regexp.MustCompile(`\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b`), `[REDACTED_EMAIL]`},
}

var defensiveContextPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)\b(defensive|defense|prevent|prevention|mitigation|detect|detection|hardening|patch|remediation|incident\s+response)\b`),
	regexp.MustCompile(`(?i)\b(do\s+not\s+provide|without\s+code|no\s+commands|high\s+level|non[-\s]?operational|refusal|unsafe)\b`),
	regexp.MustCompile(`(?i)\bprompt[-\s]?injection\s+(?:detector|detection|classifier|scanner|test)\b`),
	regexp.MustCompile(`(?i)\bdo\s+not\s+(?:follow|obey|execute|apply)\b`),
	regexp.MustCompile(`防御|防护|修复|检测|识别|排查|加固|缓解|研判|监控|告警|事件响应`),
	regexp.MustCompile(`不要提供|不提供(代码|命令|绕过|操作步骤)|不提供.{0,8}(攻击|利用|执行|操作).{0,4}(步骤|代码|命令)|仅分析.{0,20}(特征|原理|风险)`),
	regexp.MustCompile(`(?:汇总|总结|说明|介绍).{0,80}(?:检测|防御|防护|风险|告警|修复|缓解|响应|特征)`),
}

// operationalRequestPatterns deliberately require an imperative/request cue.
// Merely mentioning that an attacker can "execute" or "bypass" something in
// a report is not enough to suppress the defensive-context discount.
var operationalRequestPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)(?:^|[\n.!?;:。！？；：]\s*)(?:please\s+)?(?:write|generate|create|build|craft|make|provide|implement|execute|run|launch|deploy|install|steal|dump|extract|exfiltrate|harvest|bypass|evade|disable|exploit|attack|compromise|take\s+over|clear|delete)\b`),
	regexp.MustCompile(`(?i)\b(?:can|could|would)\s+you\b.{0,40}\b(?:write|generate|create|build|craft|make|provide|implement|execute|run|launch|deploy|install|steal|dump|extract|exfiltrate|harvest|bypass|evade|disable|exploit|attack|compromise|take\s+over|clear|delete)\b|\b(?:help\s+me|i\s+(?:want|need)|need\s+you\s+to|show\s+me\s+how\s+to|how\s+to|how\s+(?:can|do|would)\s+i)\b.{0,40}\b(?:write|generate|create|build|craft|make|provide|implement|execute|run|launch|deploy|install|steal|dump|extract|exfiltrate|harvest|bypass|evade|disable|exploit|attack|compromise|take\s+over|clear|delete)\b`),
	regexp.MustCompile(`(?i)(?:^|[\n.!?;:]\s*)(?:please\s+|now\s+)?(?:ignore|disregard|override)\b.{0,60}\b(?:previous|prior|above|system|developer|safety)\b.{0,24}\b(?:instructions?|rules?|polic(?:y|ies)|guardrails?)\b|(?:^|[\n。！？；：])\s*(?:请|请你|现在|立即)?(?:忽略|无视|覆盖).{0,30}(?:之前|以上|系统|开发者|安全).{0,12}(?:指令|规则|政策|限制)`),
	regexp.MustCompile(`(?:^|[\n。！？；：])\s*(?:(?:请|请你|帮我|给我|我要|需要你|直接|立即|马上)\s*)?(?:编写|生成|创建|构造|制作|提供|实现|执行|运行|发起|部署|安装|窃取|导出|转储|提取|外传|绕过|规避|禁用|关闭|利用|攻击|接管|清除|删除)`),
	regexp.MustCompile(`(?:请|请你|帮我|给我|我要|需要你).{0,20}(?:编写|生成|创建|构造|制作|提供|实现|执行|运行|发起|部署|安装|窃取|导出|转储|提取|外传|绕过|规避|禁用|关闭|利用|攻击|接管|清除|删除)|(?:如何|怎么)(?:实现|执行|生成|编写|绕过|窃取|攻击|利用|提权|接管|外传)`),
}

var operationalNegationPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)\b(?:do\s+not|don't|never|avoid|must\s+not|should\s+not|refuse\s+to)\s+(?:please\s+)?(?:write|generate|create|build|craft|make|provide|implement|execute|run|launch|deploy|install|steal|dump|extract|exfiltrate|harvest|bypass|evade|disable|exploit|attack|compromise|take\s+over|clear|delete)\b`),
	regexp.MustCompile(`(?:不要|不得|禁止|避免|不应|无需|拒绝).{0,6}(?:编写|生成|创建|构造|制作|提供|实现|执行|运行|发起|部署|安装|窃取|导出|转储|提取|外传|绕过|规避|禁用|关闭|利用|攻击|接管|清除|删除)`),
}

// These are concrete defensive artifacts, not generic "for research" claims.
// They prevent broad operational regexes such as "write ... steal credentials"
// from turning a Sigma-rule or remediation request into an enforcement signal.
var benignOperationalArtifactPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)\b(?:write|create|generate|build|provide|implement)\b.{0,64}\b(?:yara|sigma|snort|suricata)\b(?:.{0,20}\b(?:rule|signature)\b)?`),
	regexp.MustCompile(`(?i)\b(?:write|create|generate|build|provide|implement|develop|draft|design)\b.{0,64}\b(?:detect(?:ion|or)|monitoring|alerting|mitigation|remediation|patch|analysis|report|documentation|classifier|sensor|policy|signature|unit\s+test|test\s+fixture|indicator|ioc|yara|sigma)\b(?:.{0,32}\b(?:rule|logic|concept|code|script|guidance|test|report|model|signature|sensor|policy|template)\b)?`),
	regexp.MustCompile(`(?:编写|创建|生成|构建|提供|实现|设计).{0,48}(?:检测规则|检测思路|检测概念|告警规则|监控规则|防护规则|修复补丁|缓解方案|分析报告|报告模板|测试用例|测试夹具|检测脚本|检测代码|威胁指标|IOC)`),
}
