package promptfilter

import "strings"

type GuardProfile struct {
	Name       string                   `json:"name"`
	LayerModes map[SegmentOrigin]string `json:"layer_modes"`
}

type ProfileResolver interface {
	Resolve(RequestEnvelope, GuardConfig) GuardProfile
}

type BuiltinProfileResolver struct{}

func (BuiltinProfileResolver) Resolve(envelope RequestEnvelope, cfg GuardConfig) GuardProfile {
	cfg = NormalizeGuardConfig(cfg)
	name := cfg.DefaultProfile
	provider := strings.ToLower(strings.TrimSpace(string(envelope.ModelFamily)))
	if configured := strings.TrimSpace(cfg.ProviderProfiles[provider]); configured != "" {
		name = configured
	} else if configured := strings.TrimSpace(cfg.ProviderProfiles[string(ModelFamilyUnknown)]); configured != "" {
		name = configured
	}
	return BuiltinGuardProfile(name)
}

func BuiltinGuardProfile(name string) GuardProfile {
	name = normalizeGuardProfileName(name, GuardProfileBalanced)
	off := GuardModeOff
	inherit := GuardModeInherit
	shadow := GuardModeShadow
	warn := GuardModeWarn

	profile := GuardProfile{
		Name: name,
		LayerModes: map[SegmentOrigin]string{
			OriginCurrentUser:       inherit,
			OriginHistory:           off,
			OriginSystem:            off,
			OriginDeveloper:         off,
			OriginInstructions:      off,
			OriginToolOutput:        off,
			OriginToolArguments:     off,
			OriginAttachmentRefs:    off,
			OriginSessionContext:    off,
			OriginAttachmentContent: off,
		},
	}
	switch name {
	case GuardProfileStrict:
		profile.LayerModes[OriginHistory] = shadow
		profile.LayerModes[OriginSystem] = shadow
		profile.LayerModes[OriginDeveloper] = shadow
		profile.LayerModes[OriginInstructions] = shadow
		profile.LayerModes[OriginToolOutput] = shadow
		profile.LayerModes[OriginToolArguments] = warn
		profile.LayerModes[OriginAttachmentRefs] = shadow
		profile.LayerModes[OriginSessionContext] = shadow
		profile.LayerModes[OriginAttachmentContent] = shadow
	case GuardProfileResearch:
		profile.LayerModes[OriginToolOutput] = shadow
		profile.LayerModes[OriginToolArguments] = shadow
		profile.LayerModes[OriginAttachmentRefs] = shadow
		profile.LayerModes[OriginSessionContext] = shadow
		profile.LayerModes[OriginAttachmentContent] = shadow
	}
	return profile
}

func resolveGuardGlobalMode(cfg Config) string {
	if !cfg.Enabled {
		return GuardModeOff
	}
	mode := NormalizeGuardConfig(cfg.Advanced.Guard).Mode
	if mode != GuardModeInherit {
		return mode
	}
	switch NormalizeConfig(cfg).Mode {
	case ModeBlock:
		return GuardModeEnforce
	case ModeWarn:
		return GuardModeWarn
	default:
		return GuardModeShadow
	}
}

func resolveGuardLayerMode(cfg GuardConfig, profile GuardProfile, origin SegmentOrigin, globalMode string) string {
	// A structurally verified Codex application candidate is still untrusted
	// input and must be fully enforceable. It bypasses profile defaults only so
	// the ordinary balanced profile cannot hide it behind an auxiliary layer.
	// Strike eligibility remains disabled because the candidate was generated by
	// an application task rather than entered as the user's direct request.
	if origin == OriginApplicationCandidate {
		return capGuardMode(globalMode, globalMode)
	}
	cfg = NormalizeGuardConfig(cfg)
	configured := guardLayerMode(cfg.Layers, origin)
	if configured == GuardModeInherit {
		configured = normalizeGuardMode(profile.LayerModes[origin], GuardModeOff)
	}
	if configured == GuardModeInherit {
		configured = globalMode
	}
	resolved := capGuardMode(configured, globalMode)
	if !guardOriginCanEnforce(origin) && resolved == GuardModeEnforce {
		return GuardModeShadow
	}
	return resolved
}

func guardOriginCanEnforce(origin SegmentOrigin) bool {
	return origin == OriginCurrentUser || origin == OriginApplicationCandidate
}

func guardLayerMode(layers GuardLayerConfig, origin SegmentOrigin) string {
	switch origin {
	case OriginCurrentUser:
		return layers.CurrentUser.Mode
	case OriginHistory:
		return layers.History.Mode
	case OriginSystem:
		return layers.System.Mode
	case OriginDeveloper:
		return layers.Developer.Mode
	case OriginInstructions:
		return layers.Instructions.Mode
	case OriginToolOutput:
		return layers.ToolOutput.Mode
	case OriginToolArguments:
		return layers.ToolArguments.Mode
	case OriginAttachmentRefs:
		return layers.AttachmentRefs.Mode
	case OriginSessionContext:
		return layers.SessionContext.Mode
	case OriginAttachmentContent:
		return layers.AttachmentContent.Mode
	default:
		return GuardModeOff
	}
}

func capGuardMode(layerMode string, globalMode string) string {
	layerMode = normalizeGuardMode(layerMode, GuardModeOff)
	globalMode = normalizeGuardMode(globalMode, GuardModeShadow)
	switch globalMode {
	case GuardModeOff:
		return GuardModeOff
	case GuardModeShadow:
		if layerMode == GuardModeOff {
			return GuardModeOff
		}
		return GuardModeShadow
	case GuardModeWarn:
		if layerMode == GuardModeEnforce || layerMode == GuardModeInherit {
			return GuardModeWarn
		}
	}
	return layerMode
}
